print("WELCOME TO MAD LIB!! make sure the inputs you give are funny")

male_name       = input("enter male name :- \n")
teacher         = input("enter teacher :- \n")
exclaim         = input("enter exclaimation :- \n")
number          = input("enter number :- \n")
plural_object   = input("enter plural object :- \n")
store_name      = input("enter store name :- \n")
body_part       = input("enter body part :- \n")
silly_word      = input("enter silly word :- \n")
exclaimation    = input("enter exclaimation :- \n")
holiday         = input("enter holiday :- \n")
movie_title     = input("enter movie title :- \n")
verb            = input("enter verb ending with ing :- \n")
distance         = input("enter distance :- \n")
country         = input("enter country :- \n")
animal          = input("enter animal :- \n")
movie_quote     = input("enter movie quote :- \n")
another_bodypart            = input("enter body part:- \n")
children_song    = input("enter children song:- \n")


print(" COP: HEllo!! I am detective "+male_name+" and you are?")
print("THIEF:"+ teacher + "")
print(" COP:you are here under the suspicion of second degree robbery")
print("THIEF:" + exclaim + "")
print("COP:" + number + plural_object + "were stolen from " + store_name + " and the crime scene has your " + body_part + " written all over it")
print("THIEF: that is " + exclaimation + "")
print("COP: Where were you on the night of " + holiday + "")
print("THIEF: We were watching" + movie_title + "")
print("COP: Then why does security camera footage show you " + verb + "just" + distance + " from the crime scene")
print("COP: I am through playing games where are you from?")
print(country)
print("COP: I get to lock you up and go home to my pet " + animal + " and say " + movie_quote + "")
print("THIEF: Fine!! I committed the crime I needed it to buy myself " + another_bodypart + " implants")
print("COP: Every time I solve a crime I like to sing " + children_song + ". So sing with me!!!")
